added migrations
bcgov/PaymentCommonComponent pull request #30
Opened 2023-01-19 17:47 UTC by chelsea-EYDS

2023-01-19 17:59 UTC, chelsea-EYDS commented on apps/backend/src/database/queries/locations.ts
> +INSERT INTO public."location" (merchant_id,location_id,ax_merchant_id,pt_location_id,office_name) VALUES
Included to use as seed data for testing

2023-01-20 20:15 UTC, chelsea-EYDS commented on apps/backend/src/database/queries/locations.ts
> +export const locations = `
remove

2023-01-23 19:35 UTC, vyasworks requested changes

2023-01-23 19:35 UTC, vyasworks commented on apps/backend/src/database/config.ts
> +  synchronize: process.env.NODE_ENV === 'test' ?? false
Why should tests run with `synchronize`?

2023-01-23 19:35 UTC, vyasworks commented on apps/backend/src/database/migrations/1674455627553-migration.ts
> +import { MigrationInterface, QueryRunner } from 'typeorm';
Is this the only migration? Why is there only alter DDLs?

2023-01-23 19:38 UTC, vyasworks requested changes

2023-01-23 19:38 UTC, vyasworks commented on apps/backend/src/reconciliation/entities/location-view.entity.ts
> +  expression: `SELECT id, "GARMS Location", "Merchant ID", "Location", "description", "Type"  FROM master_location_data
this doesn't seem right

2023-01-23 19:38 UTC, vyasworks commented on apps/backend/src/reconciliation/entities/location-view.entity.ts
> +  name: 'location_view',
name does not imply what this view is

2023-01-23 21:17 UTC, vyasworks approved these changes

2023-01-23 21:20 UTC, merged