Small changes...
bcgov/PaymentCommonComponent pull request #31
Opened 2023-01-24 20:01 UTC by chelsea-EYDS

- added fiscal date
- removed location view
- migrations/ queries to insert the master location data and payment data

2023-01-26 19:57 UTC, vyasworks requested changes

2023-01-26 19:57 UTC, vyasworks commented on apps/backend/src/database/migrations/1674514238005-migration.ts
> +import { locationQuery } from '../queries/locations';
Let's exclude the data push via a migration for now.

2023-01-26 19:57 UTC, vyasworks commented on apps/backend/src/database/queries/locations.ts
> +export const locationQuery = `INSERT INTO public.master_location_data (id,"GARMS Location","Type","Location",description,"Program","Program Description","Min Client","Responsibility Code","Service Li
remove this file

2023-01-26 19:57 UTC, vyasworks commented on apps/backend/src/temp-scripts/sftp.garms.sh
we can remove this file, now that we have rclone impl

2023-01-26 19:57 UTC, vyasworks commented on apps/backend/src/temp-scripts/sftp.bcm.sh
> -    awslocal s3api put-object --bucket bc-pcc-data-files-local --key $i --body $i --metadata "type=tdi_34"
we can remove this file, now that we have rclone impl

2023-01-27 18:32 UTC, chelsea-EYDS commented
Will reopen after syncing local

2023-01-27 18:32 UTC, closed without merging