[CCFPCM-362] Cash Match
bcgov/PaymentCommonComponent pull request #58
Opened 2023-02-22 23:01 UTC by chelsea-EYDS

[CCFPCM-0362](https://bcdevex.atlassian.net/browse/CCFPCM-0362)

Objective:

2023-02-23 17:35 UTC, vyasworks requested changes

2023-02-23 17:35 UTC, vyasworks commented on apps/backend/src/reconciliation/cash-reconciliation.service.ts
> +    await Promise.all(
lets verify the output and logic of this is acceptable with Karim

2023-02-23 18:57 UTC, chelsea-EYDS commented on apps/backend/src/deposits/pos-deposit.service.ts
> +  async markPosDepositAsException(
They are always pending, by default. We could marks as in-progress and apply the same logic as with the cash match stuff where we go through and find deposits older than x number of deposits, but wouldn't this still throw an exception due to the time difference?

2023-02-23 22:12 UTC, vyasworks commented on apps/backend/src/deposits/pos-deposit.service.ts
> +  async markPosDepositAsException(
yes I meant to say in-progress

2023-02-23 23:45 UTC, chelsea-EYDS commented on apps/backend/src/deposits/cash-deposit.service.ts
> +  ): CashMatchAggregateByLocation[] {
resolved?

2023-02-23 23:45 UTC, chelsea-EYDS commented on apps/backend/src/database/migrations/1677108616249-migration.ts
> +import { MigrationInterface, QueryRunner } from 'typeorm';
Seems to be passing now?

2023-02-23 23:45 UTC, chelsea-EYDS commented on apps/backend/src/deposits/entities/pos-deposit.entity.ts
> +  //  TODO remove? This is being set on the POS Deposit Entity Match  as the join is one to one and can only be referenced from one side of the join
done :)

2023-02-23 23:45 UTC, chelsea-EYDS commented on apps/backend/src/deposits/pos-deposit.service.ts
> +      event?.location?.location_id || 0
updated

2023-02-23 23:46 UTC, chelsea-EYDS commented on apps/backend/src/deposits/pos-deposit.service.ts
> +  async markPosDepositAsException(
I didn't think POS could be inProgress based on the time match restrictions? Can we add this to a new ticket?

2023-02-23 23:47 UTC, chelsea-EYDS commented on apps/backend/src/logger/logger.service.ts
> +        new DailyRotateFile({
I thought that by setting silence based on the env that this would be taken care of?

2023-02-24 00:15 UTC, vyasworks commented on apps/backend/src/logger/logger.service.ts
> +        new DailyRotateFile({
I am not sure, we can see if it will deploy.

2023-02-24 00:18 UTC, vyasworks commented
you can run `make tag-dev` to verify deploying to dev, and see if migrations work. I am triggering it now,

2023-02-24 00:23 UTC, vyasworks commented
Migrations fail on dev: 

login to lz2 dev to see logs in `[CloudWatch](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#)
[Log groups](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups)
[/aws/lambda/migrator](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fmigrator)

![image](https://user-images.githubusercontent.com/67800715/221061488-bf31a853-92d9-4b22-a1cf-a59ce3f724f6.png)

2023-02-24 15:50 UTC, vyasworks approved these changes

2023-02-24 17:02 UTC, merged